name: Deploy HTML Map to WordPress

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Upload map via SFTP
      run: |
        lftp -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} -e "
        set sftp:auto-confirm yes;
        mirror -R html /maps/dem_world/;
        bye
        " -p ${{ secrets.SFTP_PORT }} sftp://${{ secrets.SFTP_HOST }}
