name: Deploy HTML Map to WordPress

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (optional)'
        required: false
        default: 'production'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Add host key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts

    - name: Test SFTP Connection (list directory)
      run: |
        lftp -d -e "ls" -p ${{ secrets.SFTP_PORT }} -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} sftp://${{ secrets.SFTP_HOST }}

    - name: Upload map via SFTP
      run: |
        if [ ! -d "html" ]; then
          echo "Error: html directory not found"
          exit 1
        fi
        lftp -d -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} -e "
        set net:max-retries 3;
        set net:timeout 10;
        mirror -R --verbose html /maps/dem_world;
        bye
        " -p ${{ secrets.SFTP_PORT }} sftp://${{ secrets.SFTP_HOST }}