name: Deploy HTML Map to WordPress

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (optional)'
        required: false
        default: 'production'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install lftp
  
    - name: Confirm SFTP secrets
      run: |
        echo "Testing secrets..."
        echo "SFTP_HOST: $MY_SFTP_HOST"
        echo "SFTP_PORT: $MY_SFTP_PORT"
      env:
        MY_SFTP_HOST: ${{ secrets.SFTP_HOST }}
        MY_SFTP_PORT: ${{ secrets.SFTP_PORT }}

    - name: Upload map via SFTP
      run: |
        lftp -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} -e "
        set sftp:auto-confirm yes;
        mirror -R html /maps/dem_world/;
        bye
        " -p ${{ secrets.SFTP_PORT }} sftp://${{ secrets.SFTP_HOST }}
